packages:
  - 'apps/*'
  - '!apps/editor-demo'
  - 'packages/*'

frozenLockfile: true
linkWorkspacePackages: true
preferWorkspacePackages: true
strictPeerDependencies: true

catalog:
  '@aelionsdk/core': 'workspace:*'
  '@aelionsdk/project-schema': 'workspace:*'

onlyBuiltDependencies:
  - esbuild
  - ffmpeg-static
