import type { MaterialNodeDefinition } from './types.js';

const definitions: readonly MaterialNodeDefinition[] = [
  {
    type: 'time.transition-curve',
    version: '1.0.0',
    inputs: { progress: 'float', curve: 'enum' },
    outputs: { value: 'float' },
    estimatedTextureSamples: 0,
    estimatedPasses: 0,
  },
  {
    type: 'composite.mix',
    version: '1.0.0',
    inputs: { a: 'visual-frame', b: 'visual-frame', amount: 'float' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 2,
    estimatedPasses: 1,
  },
  {
    type: 'color.temperature',
    version: '1.0.0',
    inputs: { source: 'visual-frame', amount: 'float' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 1,
    estimatedPasses: 0,
  },
  {
    type: 'color.lift-black',
    version: '1.0.0',
    inputs: { source: 'visual-frame', amount: 'float' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 1,
    estimatedPasses: 0,
  },
  {
    type: 'color.extract-highlights',
    version: '1.0.0',
    inputs: { source: 'visual-frame', threshold: 'float' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 1,
    estimatedPasses: 1,
  },
  {
    type: 'blur.gaussian',
    version: '1.0.0',
    inputs: { source: 'visual-frame', radiusPx: 'float' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 16,
    estimatedPasses: 2,
  },
  {
    type: 'color.scale-rgb',
    version: '1.0.0',
    inputs: { source: 'visual-frame', scale: 'float' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 1,
    estimatedPasses: 0,
  },
  {
    type: 'composite.screen',
    version: '1.0.0',
    inputs: { base: 'visual-frame', overlay: 'visual-frame' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 2,
    estimatedPasses: 1,
  },
  {
    type: 'math.add',
    version: '1.0.0',
    inputs: { a: 'float', b: 'float' },
    outputs: { value: 'float' },
    estimatedTextureSamples: 0,
    estimatedPasses: 0,
  },
  {
    type: 'math.subtract',
    version: '1.0.0',
    inputs: { a: 'float', b: 'float' },
    outputs: { value: 'float' },
    estimatedTextureSamples: 0,
    estimatedPasses: 0,
  },
  {
    type: 'math.multiply',
    version: '1.0.0',
    inputs: { a: 'float', b: 'float' },
    outputs: { value: 'float' },
    estimatedTextureSamples: 0,
    estimatedPasses: 0,
  },
  {
    type: 'math.divide',
    version: '1.0.0',
    inputs: { a: 'float', b: 'float' },
    outputs: { value: 'float' },
    estimatedTextureSamples: 0,
    estimatedPasses: 0,
  },
  {
    type: 'math.clamp',
    version: '1.0.0',
    inputs: { value: 'float', min: 'float', max: 'float' },
    outputs: { value: 'float' },
    estimatedTextureSamples: 0,
    estimatedPasses: 0,
  },
  {
    type: 'math.smoothstep',
    version: '1.0.0',
    inputs: { edge0: 'float', edge1: 'float', x: 'float' },
    outputs: { value: 'float' },
    estimatedTextureSamples: 0,
    estimatedPasses: 0,
  },
  {
    type: 'color.exposure',
    version: '1.0.0',
    inputs: { source: 'visual-frame', stops: 'float' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 1,
    estimatedPasses: 0,
  },
  {
    type: 'color.contrast',
    version: '1.0.0',
    inputs: { source: 'visual-frame', amount: 'float' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 1,
    estimatedPasses: 0,
  },
  {
    type: 'color.saturation',
    version: '1.0.0',
    inputs: { source: 'visual-frame', amount: 'float' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 1,
    estimatedPasses: 0,
  },
  {
    type: 'color.invert',
    version: '1.0.0',
    inputs: { source: 'visual-frame' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 1,
    estimatedPasses: 0,
  },
  {
    type: 'composite.multiply',
    version: '1.0.0',
    inputs: { base: 'visual-frame', overlay: 'visual-frame' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 2,
    estimatedPasses: 1,
  },
  {
    type: 'composite.add',
    version: '1.0.0',
    inputs: { base: 'visual-frame', overlay: 'visual-frame' },
    outputs: { frame: 'visual-frame' },
    estimatedTextureSamples: 2,
    estimatedPasses: 1,
  },
];

export const VISUAL_NODE_SET_1 = new Map(
  definitions.map(definition => [`${definition.type}@${definition.version}`, definition]),
);

export const VISUAL_NODE_SET_1_DEFINITIONS = definitions;
